library()
getwd()
setwd("E:/R Data")
expensedata <- read.csv("SpendHistory.csv")
View(expensedata)
expensedata2 <- filter(expensedata,Amount > 0)
View(expensedata2)
total <- summarise(group_by(expensedata2,Category),sum(Amount))
View(total)
